blank_issues_enabled: false
contact_links:
  - name: 📚 Development Guide
    url: https://github.com/tonyroy/skills-expand-your-team-with-copilot/blob/main/docs/how-to-develop.md
    about: Instructions for setting up and developing the school activities website
  - name: 💬 General Questions
    url: https://github.com/tonyroy/skills-expand-your-team-with-copilot/discussions
    about: Ask questions or start discussions about the project