name: 🚀 Feature Request
description: Request a new feature or enhancement for the school activities website
title: "[Feature]: "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide as much detail as possible to help us understand what you need.

  - type: input
    id: feature-title
    attributes:
      label: Feature Title
      description: A clear, concise title for your feature request
      placeholder: "Add ability to filter activities by grade level"
    validations:
      required: true

  - type: textarea
    id: problem-description
    attributes:
      label: Problem Description
      description: What problem does this feature solve? Who would benefit from it?
      placeholder: "Currently, students see all activities mixed together, making it hard for freshmen to find beginner-friendly activities..."
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe what you want to happen. Be as specific as possible.
      placeholder: "Add a dropdown filter that allows students to filter activities by recommended grade level (9th, 10th, 11th, 12th, All)"
    validations:
      required: true

  - type: dropdown
    id: feature-category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - User Interface / Design
        - Search & Filtering
        - User Account Features
        - Activity Management
        - Data Display
        - Other
    validations:
      required: true

  - type: dropdown
    id: user-type
    attributes:
      label: Primary Users
      description: Who would primarily use this feature?
      options:
        - Students
        - Teachers
        - Both Students and Teachers
        - Administrators
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: How will we know this feature is complete? List specific requirements.
      placeholder: |
        - [ ] Filter dropdown appears in the sidebar
        - [ ] Selecting a grade level shows only relevant activities
        - [ ] "All" option shows activities for all grade levels
        - [ ] Filter persists when navigating between pages
      value: |
        - [ ] 
        - [ ] 
        - [ ] 
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature?
      options:
        - Low - Nice to have
        - Medium - Would improve user experience
        - High - Needed for basic functionality
        - Critical - Blocking important workflows
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information, mockups, examples, or constraints we should know about?
      placeholder: "This was requested by several students during our focus group. Similar feature exists on the district's sports website."

  - type: textarea
    id: technical-hints
    attributes:
      label: Technical Hints (Optional)
      description: If you have any technical suggestions or know of similar implementations, please share them here.
      placeholder: "Could use JavaScript to filter the activity cards, similar to how the search function works"

  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      description: Please confirm you understand the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I understand this will be implemented by AI coding assistants and have provided sufficient detail
          required: true